version: "3.9"

services:

  postgres:
    restart: always
    image: postgres:latest
    container_name: shop_db
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./init_database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - pg_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8088:8088"
    environment:
      PGDB: shop
      PGUSER: user
      PGPASSWORD: test
      PGHOST: shop_db
      PGPORT: 5432
      PORT: 8088
    depends_on:
      - postgres
    command:
      - ./wait-for-postgres.sh

volumes:
  pg_db:
  init_database: